### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by xelotex** [bl4ckscor3/ParticleCulling#2] opened 2021-01-25 00:31 UTC
[crash-2021-01-24_18.01.56-client.txt](https://github.com/bl4ckscor3/ParticleCulling/files/5863528/crash-2021-01-24_18.01.56-client.txt)

**Comment by bl4ckscor3** [comment] 2021-01-25 01:59
Try updating JustEnoughIDs. Please comment whether this works for you.

**Comment by bl4ckscor3** [comment] 2021-01-31 13:55
I am closing this issue as I cannot reproduce it on my end, nor can I attribute the crash to Particle Culling. Please provide a minimal testing environment (aka, the minimum amount of mods and their versions with which this is reproducible), and I'll happily see if it's Particle Culling's fault, and if so, try and fix it.

**Closed as completed by bl4ckscor3** 2021-01-31 13:55 UTC

**Comment by xelotex** [comment] 2021-01-31 22:21
i tried to update JustEnoughIDs but that didn't work, it stills crashing, how i can give you my modpack for you test this issue? github doesn't let me paste files that are bigger than 10MB, sorry for being 8 days late to reply to you but i miss the notification.

**Comment by bl4ckscor3** [comment] 2021-01-31 22:53
I have two more ideas. Try [updating Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge/files/2919497) as well as JEID. If that does not fix it, try using [Mixin 0.7-0.8 Compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility/files/3045381).

**Comment by xelotex** [comment] 2021-02-01 00:23
mixin compat fix this, thanks.
