### ISSUE TITLE
Dropped item entity flickers on pickup

### ISSUE THREAD

**Issue by xJon** [bl4ckscor3/ParticleCulling#12] opened 2024-05-12 03:47 UTC
Does not happen when Particle Culling is removed (disabling the culling does not remedy this).
![image](https://github.com/bl4ckscor3/ParticleCulling/assets/8945347/a0175cff-6e3e-4d42-8b23-3849bae51b43)

https://github.com/bl4ckscor3/ParticleCulling/assets/8945347/481d4caa-a676-4233-a464-df3b8fc4b772

**Comment by bl4ckscor3** [comment] 2024-05-12 08:29
~~While I can reproduce this, I am very stumped on why this happens, as Particle Culling does not touch item entities at all. Item entities are not particles, they are rendered in a completely different way. I can also not consistently reproduce this with Particle Culling, it only happens sometimes.~~

~~Do you perhaps have Entity Culling installed? While it doesn't make sense that I'd be able to recreate the issue with only my mod, it could have some remedy for this.~~


EDIT: Nevermind, turns out the pickup animation is a particle.

**Comment by bl4ckscor3** [comment] 2024-05-12 09:08
Fixed by 6222dd17830b818ff09994f567674450bb968610 and 2a01d713d9e4045354aadf95013973867a1c15f2

Part of the fix was adding the item pickup particle to the default ignore list. The list needs to be updated in existing configs manually with `net.minecraft.client.particle.ParticleItemPickup`.

**Closed as completed by bl4ckscor3** 2024-05-12 09:08 UTC
Labels: bug
