### ISSUE TITLE
Particles Die with Integrated Dynamics Interaction when antempting to cull particle

### ISSUE THREAD

**Issue by Shibva** [bl4ckscor3/ParticleCulling#9] opened 2024-02-28 01:44 UTC
```
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.block.collidable.CollidableComponentParts.getPartBoundingBox(CollidableComponentParts.java:33)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.block.collidable.CollidableComponentParts.getBounds(CollidableComponentParts.java:54)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.block.collidable.CollidableComponentParts.getBounds(CollidableComponentParts.java:29)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.core.block.CollidableComponent.doRayTraceComponent(CollidableComponent.java:125)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.core.block.CollidableComponent.doRayTrace(CollidableComponent.java:148)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.core.block.CollidableComponent.collisionRayTrace(CollidableComponent.java:70)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.cyclops.integrateddynamics.block.BlockCable.func_180636_a(BlockCable.java:126)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:473)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at bl4ckscor3.mod.particleculling.CullThread.shouldCull(CullThread.java:226)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at bl4ckscor3.mod.particleculling.CullThread.shouldCullParticle(CullThread.java:110)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at bl4ckscor3.mod.particleculling.CullThread.iterateParticles(CullThread.java:83)
[20:42:53] [Particle Culling/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at bl4ckscor3.mod.particleculling.CullThread.run(CullThread.java:44)
```

**Comment by bl4ckscor3** [comment] 2024-02-28 11:51
Which Integrated Dynamics version are you using?

**Comment by Shibva** [comment] 2024-02-28 17:54
Their latest version posted for 12.2

Sorry forgot to include that

**Comment by bl4ckscor3** [comment] 2024-02-28 22:55
Thank you! I will look into this.
Note: While it's unlikely that you are not using the actually latest version of Integrated Dynamics due to it having been released quite a few years back, please *never* say "latest" when asked for the version number of anything. It is vague and ambiguous, and no one but you can verify whether the actual latest version is the version that you think is latest. Using the proper version number makes sure there is no misunderstanding!

**Comment by Shibva** [comment] 2024-02-28 22:56
Yeah, I was actually thinking that on the back of my head about saying that; I only said that because I wasn't at my computer at the time to pull up the last release for 12.2; sorry about that give me a moment

**Comment by Shibva** [comment] 2024-02-28 23:23
-------------alright

its Integrated Dynamics 1.12.2-1.1.11
https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics/files/3159505

would like to note that their block collisions are a bit odd, if the outline (fencing) is an indicator of that lel

EDIT: I also have Integrated Tunnels for this version as well, just to make that known in case its relivent

**Comment by Shibva** [comment] 2024-03-03 00:48
to add on, this issue stops if I disable the mod via the clientside toggle option 

and while I have confirmed this issue occurs with the normal Minecraft particles, I am also using Fancier Block Particles
https://www.curseforge.com/minecraft/mc-mods/fbp/files/4032588
again, I have confirmed this issue without this present but am adding this just in case for whatever reason it does or makes the issue more likey to happen

also it seems that particles die as well if you have a UI open for too long but I cant 100% confirm this confidently

as for a means of reproducing, please let me know if that's needed; same goes if you need a full game log

**Comment by bl4ckscor3** [comment] 2024-03-05 20:23
I played a bit around and couldn't quite figure out a case where this occurs. Reproduction steps would be appreciated! Your Particle Culling config would also be helpful, please.

**Comment by Shibva** [comment] 2024-03-05 20:56
I'll see what I can do; it might be difficult 

If there is a way I can extend my log while reproducing it please let me know

I'll get back when I can

**Comment by bl4ckscor3** [comment] 2024-03-05 23:00
You can post the log on https://gist.github.com and post the link here if you want.

**Comment by Shibva** [comment] 2024-03-08 06:31
I think it will have a higher chance of occurring if you do the following, I haven't tested it but this is close to the situation that has caused the fault so If im correct this should work

1. get `Logic Cable` and place them in the shape of a 5x5x5 hollow box, with all of their faces covered as well.
2. get a crafting table, any block, and a facade.
3. place the table and open it, put the block you chose and the facade in there; this is needed as the facade on its own cannot be applied; it requires a block crafted with it to use its texture before it can be placable on logic cables
4. right click all the logic cable blocks with the output of step 3 to apply them; for best measure, apply them to all.
5. once that's done, go ahead and break a hole in the center of the top face of your cube

6. this one is going to have to be up to you; the objective here is to have particles occur inside this box. Do whatever you can to create a good amount of particles in here; doesn't matter what as long as these particles are using minecrafts particle system and not an independent one (embers, astral sorcery, etc). The likeyhood of this bug happening increases in theory the more particles are in this hallowed cube. if you spawn enough of them and then obstruct you view by flying away from the small hole and stay nearby the box, it will occur. To make things easier, once your done doing whatever you did to spew out a bunch of particles, go ahead and wait by the side of the box where its obstructed and place something that gives off particles. This is not important but it will easy for you to indicate when the particle engine stops working when (for example; a torch) stops emitting vanilla particles.

7. if nothing happens within five minutes, repeat 1-6 except with a smaller box (3x3x3) or layer up

**Comment by bl4ckscor3** [comment] 2024-03-08 10:57
Thanks a lot! I thought of a possible fix for this, and included it in [this updated mod file](https://cdn.discordapp.com/attachments/402175060716158986/1215614129805594624/particleculling-1.12.2-v1.4.2.jar?ex=660fd8e1&is=65fd63e1&hm=0dfe6dffb2d0c64ed693f41d254fd59435b56773c075310c9fd9f00a91abb546&). It'd be very much appreciated if you could test it out and report back whether the issue still happens for you.

**Comment by Shibva** [comment] 2024-04-01 19:17
Oh! Sorry I dint think you game me a testmod file

Sure I will give it a shot;

**Comment by Shibva** [comment] 2024-04-03 06:38
ok It seems like its patched. Ill let you know if its acting up again

**Comment by bl4ckscor3** [comment] 2024-04-03 09:17
Thank you for checking! I will release the new version properly.

**Closed as completed** 2024-04-03 09:17 UTC
Labels: bug
